#!/bin/sh

#Add this to your autoexec

picom &
xinput --set-prop 13 "libinput Accel Speed" -1 &
sxhkd &
nitrogen --restore &
dunst &
dwmblocks &

while true; do
    # Log stderror to a file
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
